config/routes.rb
Rails.application.routes.draw do
  resources :items do
    collection do
      post 'upload_item_picture'
    end
  end

  resources :materials

        
end

app/models/item.rb
class Item < ActiveRecord::Base  
  has_many :items_materials
  has_many :materials, through: :item_materials

  mount_base64_uploader :picture, ImageUploader
end

app/models/item_Material.rb
class ItemMaterial < ActiveRecord::Base
  belongs_to :items
  belongs_to :materials
end

app/models/material.rb
class Material < ActiveRecord::Base
  has_many :items_materials
  has_many :items, through: :item_materials
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
# Item Controller As API
class ItemsController < ApplicationController
  include ItemsHelper
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /items
  # GET /items.json
  def index
    @items = get_all_modif(Item.all)
  end

  # GET /items/1
  # GET /items/1.json
  def show
    item = params[:id] && Item.find_by(id: params[:id])
    if item
      item_material = ItemMaterial.where(item_id: params[:id])
      @item = item
      @material_list = []
      materials = Material.all

      item_material.each do |item_code|
        @material_list.push(materials.find_by(id: item_code.material_id))
      end

    else
      json_blank(404, 'Item cannot be found.')
    end
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upload_item_picture
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Only allow the white list through.
  def item_params
    params.require(:item).permit(:name, :rank, :description, :status, :picture)
  end
end

app/controllers/items_materials_controller.rb
class ItemsMaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]
  skip_before_filter  :verify_authenticity_token

  # GET /items_materials
  # GET /items_materials.json
  def index
    @items_materials = ItemMaterial.all
  end

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]
	skip_before_filter  :verify_authenticity_token

# GET /materials
  # GET /materials.json
  def index
	@materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
	@material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
	@material = Material.new(material_params)

	respond_to do |format|
	  if @material.save
		format.html { redirect_to @material, notice: 'Material was successfully created.' }
		format.json { render :show, status: :created, location: @material }
	  else
		format.html { render :new }
		format.json { render json: @material.errors, status: :unprocessable_entity }
	  end
	end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
	respond_to do |format|
	  if @material.update(material_params)
		format.html { redirect_to @material, notice: 'Material was successfully updated.' }
		format.json { render :show, status: :ok, location: @material }
	  else
		format.html { render :edit }
		format.json { render json: @material.errors, status: :unprocessable_entity }
	  end
	end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
	@material.destroy
	respond_to do |format|
	  format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
	  format.json { head :no_content }
	end
  end

  private
	# Use callbacks to share common setup or constraints between actions.
	def set_material
	  @material = Material.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def material_params
	  params.require(:material).permit(:name, :unit, :quantity)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper

  def get_all_modif(item_list)
    #item_list = Item.all
    material_list = Material.all
    item_material_list = ItemMaterial.all

    item_list.each do |item_one|
      @item_material_raw = item_material_list.where(item_id: item_one.id).all
      
      #byebug
      #item_one.picture = (item_one.picture.url.to_s != '') ? 'http://localhost:3000/' + item_one.picture.url.to_s : item_one.picture.url
      #item_one.picture.url =  'http://localhost:3000/' + item_one.picture.url.to_s

      @item_material_raw.each do |raw_item|
        @real_qty = material_list.where(id: raw_item.material_id).first.quantity

        if !(@real_qty >= raw_item.quantity)
          item_one.status = false
          break
        else
          item_one.status = true
        end
      end

      item_list.where(id: item_one.id).first.update(status: item_one.status)
    end
  end

end

app/helpers/materials_helper.rb
module MaterialsHelper
    
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.text_field :rank %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rank</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.rank %></td>
        <td><%= item.description %></td>
        <td><%= item.status %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @item.picture_url.to_s %>
</p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @item.rank %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Synthesis</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/materials/_form.html.erb
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing Material</h1>

<%= render 'form' %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Materials</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rank</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.name %></td>
        <td><%= material.unit %></td>
        <td><%= material.quantity %></td>
       
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material', new_material_path %>

app/views/materials/new.html.erb
<h1>New Material</h1>

<%= render 'form' %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @material.name %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @material.unit %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @material.quantity %>
</p>

<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>